export default {
  ON_CONTACTS_LOAD_SUCCESS: 'ON_CONTACTS_LOAD_SUCCESS',
  ON_CONTACTS_LOAD_FAILED: 'ON_CONTACTS_LOAD_FAILED',
  CONTACT_ADDRESS_EDIT_SUCCESS: 'CONTACT_ADDRESS_EDIT_SUCCESS',
  CONTACT_ADDRESS_EDIT_FAILED: 'CONTACT_ADDRESS_EDIT_FAILED',
  CONTACT_TELEPHONE_EDIT_SUCCESS: 'CONTACT_TELEPHONE_EDIT_SUCCESS',
  CONTACT_TELEPHONE_EDIT_FAILED: 'CONTACT_TELEPHONE_EDIT_FAILED',
  CONTACT_EMAIL_EDIT_SUCCESS: 'CONTACT_EMAIL_EDIT_SUCCESS',
  CONTACT_EMAIL_EDIT_FAILED: 'CONTACT_EMAIL_EDIT_FAILED'
};
